name: Test Resp Writer Reader

on:
  push:
    branches: [ "resp-writer" ]
  pull_request:
    branches: [ "resp-writer" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./internal/resp

    - name: Test
      run: go test -v ./internal/resp

    - name: FuzyTest
      run: go test -v ./internal/resp -fuzz=Fuzz -fuzztime 10s
